# data.py

# Xhosa Vocabulary
xhosa_data = {
    "Pronouns": {"I/me": "mna", "you": "wena", "he/she": "yena", "we/us": "thina", "you all": "nina", "they": "bona",
                 "it’s me": "ndim", "it’s you": "nguwe", "it’s him/her": "nguye", "it’s us": "sithina",
                 "it’s you all": "ninina", "it’s them": "ngabo"},
    "Basic Verbs": {"to go": "ukuhamba", "to see": "ukubona", "to speak": "ukuthetha", "to hear": "ukuva",
                    "to work": "ukusebenza", "to learn": "ukufunda", "to write": "ukubhala", "to come": "ukuza",
                    "to live": "ukuphila", "to like": "ukuthanda", "to want": "ukufuna", "to give": "ukunika",
                    "to take": "ukuthatha", "to know": "ukwazi", "to think": "ukucinga", "to tell": "ukuxelela",
                    "to sleep": "ukulala", "to wake up": "ukuvuka", "to fish": "ukuloba", "to swim": "ukuqubha",
                    "to cook": "ukupheka", "to grill": "ukuosa", "to boil": "ukubilisa", "to cut": "ukusika",
                    "to wash": "ukuhlamba", "to shower": "ukugeza", "to walk": "ukuhamba ngeenyawo", "to shop": "ukuthenga",
                    "to need": "ukufuna", "to get up": "ukuvuka ekuseni"},
    "Nouns": {"person": "umntu", "people": "abantu", "thing": "into", "things": "izinto", "place": "indawo",
              "time": "ixesha", "day": "imini", "today": "namhlanje", "night": "ubusuku", "work": "umsebenzi",
              "family": "usapho", "friend": "umhlobo", "friends": "abahlobo", "name": "igama", "language": "ulwimi",
              "money": "imali", "food": "ukutya", "book": "incwadi", "school": "isikolo", "water": "amanzi",
              "sea": "ulwandle", "beach": "ibhishi", "fish": "intlanzi", "boat": "inqanawa", "house": "indlu",
              "door": "umnyango", "window": "ifestile", "table": "itafile", "chair": "isitulo", "bed": "ibhedi",
              "room": "igumbi", "kitchen": "ikhitshi", "meal": "isidlo", "meat": "inyama", "egg": "iqanda",
              "stew": "isitshwala", "pan": "ipani", "stove": "isitovu", "fire": "umlilo", "pot": "imbiza",
              "soap": "isepha"},
    "Question Words": {"why": "ngoba", "how": "njani", "where": "phi", "what": "yini", "what thing": "ntoni",
                       "how much/how many": "kangakanani", "when": "xeshikweni", "who": "ngubani"},
    "Connectors": {"and": "na", "but": "kodwa", "or": "okanye", "because": "kuba", "when": "xa", "if": "ukuba",
                   "then/so": "ke", "therefore": "ngoko", "however": "kanti", "just": "nje"},
    "Descriptive Terms": {"very/much": "kakhulu", "little": "kancinci", "everything/all": "konke", "nothing": "nto",
                          "another": "elinye", "many": "okuninzi", "few": "okumbalwa", "quickly": "ngokukhawuleza",
                          "slowly": "kancane", "often": "rhoqo", "sometimes": "ngamanye amaxesha", "above/more": "ngaphezulu",
                          "below/less": "ngaphantsi", "between/inside": "phakathi", "beside": "ecaleni", "far": "kude",
                          "near": "kufutshane", "beautiful": "mhle", "ugly/bad": "mbi", "hard/difficult": "lukhuni",
                          "easy": "lula", "hot": "shushu", "cold": "banda", "nice/tasty": "mnandi", "busy": "xakekile"},
    "Numbers": {"zero": "iqanda", "one": "enye", "two": "zimbini", "three": "zintathu", "four": "zine", "five": "zintlanu",
                "six": "zintandathu", "seven": "zisixhenxe", "eight": "zisibhozo", "nine": "zithoba", "ten": "zilishumi",
                "eleven": "zilishumi elinanye", "twelve": "zilishumi elinesibini", "thirteen": "zilishumi elinesithathu",
                "fourteen": "zilishumi elinesine", "twenty": "amashumi amabini", "twenty-one": "amashumi amabini ananye",
                "twenty-two": "amashumi amabini anesibini", "twenty-three": "amashumi amabini anesithathu",
                "thirty": "amashumi amathathu", "thirty-one": "amashumi amathathu ananye", "thirty-two": "amashumi amathathu anesibini",
                "thirty-three": "amashumi amathathu anesithathu", "forty": "amashumi amane", "forty-one": "amashumi amane ananye",
                "forty-two": "amashumi amane anesibini", "forty-three": "amashumi amane anesithathu", "fifty": "amashumi amahlanu",
                "fifty-one": "amashumi amahlanu ananye", "fifty-two": "amashumi amahlanu anesibini", "fifty-three": "amashumi amahlanu anesithathu",
                "sixty": "amashumi amathandathu", "sixty-one": "amashumi amathandathu ananye", "sixty-two": "amashumi amathandathu anesibini",
                "sixty-three": "amashumi amathandathu anesithathu", "seventy": "amashumi asixhenxe", "seventy-one": "amashumi asixhenxe ananye",
                "seventy-two": "amashumi asixhenxe anesibini", "seventy-three": "amashumi asixhenxe anesithathu",
                "eighty": "amashumi asibhozo", "eighty-one": "amashumi asibhozo ananye", "eighty-two": "amashumi asibhozo anesibini",
                "eighty-three": "amashumi asibhozo anesithathu", "ninety": "amashumi alithoba", "ninety-one": "amashumi alithoba ananye",
                "ninety-two": "amashumi alithoba anesibini", "ninety-three": "amashumi alithoba anesithathu", "one hundred": "ikhulu"},
    "Weekdays/Months": {"Monday": "uMvulo", "Tuesday": "uLwesibini", "Wednesday": "uLwesithathu", "Thursday": "uLwesine",
                        "Friday": "uLwesihlanu", "Saturday": "uMgqibelo", "Sunday": "iCawe", "January": "uJanuwari",
                        "February": "uFebruwari", "March": "uMatshi", "April": "uApreli", "May": "uMeyi", "June": "uJuni",
                        "July": "uJulayi", "August": "uAgasti", "September": "uSeptemba", "October": "uOkthoba",
                        "November": "uNovemba", "December": "uDisemba"},
    "Simple Sentences": {
        "I am going to cook": "Ndiza kupheka",
        "I am cooking": "Ndiyapheka",
        "I am going to shower": "Ndiza kugeza",
        "I am showering": "Ndiyageza",
        "I am working": "Ndiyasebenza",
        "I am going for a walk": "Ndiza kuhamba ngeenyawo",
        "Let’s go to the beach": "Masiye elwandle",
        "Let’s go fishing": "Masiyokuloba",
        "I want to go fishing": "Ndifuna ukuya kuloba",
        "Are we going shopping?": "Siya kuthenga?",
        "What do we need?": "Sifuna ntoni?",
        "I am getting up": "Ndiyavuka ekuseni",
        "I need water": "Ndifuna amanzi",
        "I am busy today": "Ndixakekile namhlanje",
        "It’s hot today": "Kuyashushu namhlanje",
        "It’s cold today": "Kuyabanda namhlanje",
        "I like cooking meat": "Ndiyathanda ukupheka inyama",
        "I want to see the sea": "Ndifuna ukubona ulwandle",
        "We are going to the kitchen": "Siya ekhitshini",
        "I am taking a nap": "Ndiyalala kancinci",
        "Let’s cook stew": "Masipheke isitshwala",
        "I need soap": "Ndifuna isepha",
        "I am washing the pan": "Ndiyahlamba ipani",
        "Are you working?": "Uyasebenza?",
        "I want to go to the beach": "Ndifuna ukuya elwandle",
        "Let’s walk today": "Masihambe ngeenyawo namhlanje",
        "I am cutting meat": "Ndiyasika inyama",
        "We need food": "Sifuna ukutya",
        "I am boiling water": "Ndiyabilisa amanzi",
        "I like fishing": "Ndiyathanda ukuloba",
        "Let’s go to the house": "Masiye endlwini",
        "I am going to work": "Ndiya emsebenzini",
        "I need a chair": "Ndifuna isitulo",
        "Are we cooking tonight?": "Siyapheka ngokuhlwa?",
        "I want to sleep": "Ndifuna ukulala",
        "Let’s see the fish": "Masibone intlanzi",
        "I am grilling today": "Ndiyosa namhlanje",
        "We are shopping": "Siyathenga",
        "What time are we going?": "Sihamba ngeliphi ixesha?",
        "I need a pot": "Ndifuna imbiza",
        "I am waking up early": "Ndiyavuka ekuseni kakhulu",
        "Let’s take the boat": "Masithathe inqanawa",
        "I like the beach": "Ndiyathanda ibhishi",
        "I am going to the room": "Ndiya egumbini",
        "We need money": "Sifuna imali",
        "I want to wash": "Ndifuna ukuhlamba",
        "Are you fishing?": "Uyaloba?",
        "I am cooking eggs": "Ndiyapheka amaqanda",
        "Let’s go to the fire": "Masiye emlilweni",
        "I need to know": "Ndifuna ukwazi"
    }
}

# Spanish Vocabulary
spanish_data = {
    "Pronouns": {"I/me": "yo", "you": "tú", "he/she": "él/ella", "we/us": "nosotros", "you all": "ustedes",
                 "they": "ellos/ellas", "it’s me": "soy yo", "it’s you": "eres tú", "it’s him/her": "es él/ella",
                 "it’s us": "somos nosotros", "it’s you all": "son ustedes", "it’s them": "son ellos/ellas"},
    "Basic Verbs": {"to go": "ir", "to see": "ver", "to speak": "hablar", "to hear": "oír", "to work": "trabajar",
                    "to learn": "aprender", "to write": "escribir", "to come": "venir", "to live": "vivir",
                    "to like": "gustar", "to want": "querer", "to give": "dar", "to take": "tomar", "to know": "saber",
                    "to think": "pensar", "to tell": "decir", "to sleep": "dormir", "to wake up": "despertar",
                    "to fish": "pescar", "to swim": "nadar", "to cook": "cocinar", "to grill": "asar",
                    "to boil": "hervir", "to cut": "cortar", "to wash": "lavar", "to shower": "bañarse",
                    "to walk": "caminar", "to shop": "comprar", "to need": "necesitar", "to get up": "levantarse"},
    "Nouns": {"person": "persona", "people": "gente", "thing": "cosa", "things": "cosas", "place": "lugar",
              "time": "tiempo", "day": "día", "today": "hoy", "night": "noche", "work": "trabajo",
              "family": "familia", "friend": "amigo", "friends": "amigos", "name": "nombre", "language": "idioma",
              "money": "dinero", "food": "comida", "book": "libro", "school": "escuela", "water": "agua",
              "sea": "mar", "beach": "playa", "fish": "pescado", "boat": "barco", "house": "casa",
              "door": "puerta", "window": "ventana", "table": "mesa", "chair": "silla", "bed": "cama",
              "room": "cuarto", "kitchen": "cocina", "meal": "comida", "meat": "carne", "egg": "huevo",
              "stew": "guiso", "pan": "sartén", "stove": "estufa", "fire": "fuego", "pot": "olla",
              "soap": "jabón"},
    "Question Words": {"why": "por qué", "how": "cómo", "where": "dónde", "what": "qué", "what thing": "qué cosa",
                       "how much/how many": "cuánto", "when": "cuándo", "who": "quién"},
    "Connectors": {"and": "y", "but": "pero", "or": "o", "because": "porque", "when": "cuando", "if": "si",
                   "then/so": "entonces", "therefore": "por lo tanto", "however": "sin embargo", "just": "solo"},
    "Descriptive Terms": {"very/much": "muy", "little": "poco", "everything/all": "todo", "nothing": "nada",
                          "another": "otro", "many": "muchos", "few": "pocos", "quickly": "rápido", "slowly": "despacio",
                          "often": "a menudo", "sometimes": "a veces", "above/more": "arriba/más", "below/less": "abajo/menos",
                          "between/inside": "entre/adentro", "beside": "al lado", "far": "lejos", "near": "cerca",
                          "beautiful": "hermoso", "ugly/bad": "malo", "hard/difficult": "difícil", "easy": "fácil",
                          "hot": "caliente", "cold": "frío", "nice/tasty": "rico", "busy": "ocupado"},
    "Numbers": {"zero": "cero", "one": "uno", "two": "dos", "three": "tres", "four": "cuatro", "five": "cinco",
                "six": "seis", "seven": "siete", "eight": "ocho", "nine": "nueve", "ten": "diez",
                "eleven": "once", "twelve": "doce", "thirteen": "trece", "fourteen": "catorce",
                "twenty": "veinte", "twenty-one": "veintiuno", "twenty-two": "veintidós", "twenty-three": "veintitrés",
                "thirty": "treinta", "thirty-one": "treinta y uno", "thirty-two": "treinta y dos", "thirty-three": "treinta y tres",
                "forty": "cuarenta", "forty-one": "cuarenta y uno", "forty-two": "cuarenta y dos", "forty-three": "cuarenta y tres",
                "fifty": "cincuenta", "fifty-one": "cincuenta y uno", "fifty-two": "cincuenta y dos", "fifty-three": "cincuenta y tres",
                "sixty": "sesenta", "sixty-one": "sesenta y uno", "sixty-two": "sesenta y dos", "sixty-three": "sesenta y tres",
                "seventy": "setenta", "seventy-one": "setenta y uno", "seventy-two": "setenta y dos", "seventy-three": "setenta y tres",
                "eighty": "ochenta", "eighty-one": "ochenta y uno", "eighty-two": "ochenta y dos", "eighty-three": "ochenta y tres",
                "ninety": "noventa", "ninety-one": "noventa y uno", "ninety-two": "noventa y dos", "ninety-three": "noventa y tres",
                "one hundred": "cien"},
    "Weekdays/Months": {"Monday": "lunes", "Tuesday": "martes", "Wednesday": "miércoles", "Thursday": "jueves",
                        "Friday": "viernes", "Saturday": "sábado", "Sunday": "domingo", "January": "enero",
                        "February": "febrero", "March": "marzo", "April": "abril", "May": "mayo", "June": "junio",
                        "July": "julio", "August": "agosto", "September": "septiembre", "October": "octubre",
                        "November": "noviembre", "December": "diciembre"},
    "Simple Sentences": {
        "I am going to cook": "Voy a cocinar",
        "I am cooking": "Estoy cocinando",
        "I am going to shower": "Voy a bañarme",
        "I am showering": "Estoy bañándome",
        "I am working": "Estoy trabajando",
        "I am going for a walk": "Voy a caminar",
        "Let’s go to the beach": "Vamos a la playa",
        "Let’s go fishing": "Vamos a pescar",
        "I want to go fishing": "Quiero ir a pescar",
        "Are we going shopping?": "¿Vamos a comprar?",
        "What do we need?": "¿Qué necesitamos?",
        "I am getting up": "Me estoy levantando",
        "I need water": "Necesito agua",
        "I am busy today": "Estoy ocupado hoy",
        "It’s hot today": "Hace calor hoy",
        "It’s cold today": "Hace frío hoy",
        "I like cooking meat": "Me gusta cocinar carne",
        "I want to see the sea": "Quiero ver el mar",
        "We are going to the kitchen": "Vamos a la cocina",
        "I am taking a nap": "Estoy durmiendo un poco",
        "Let’s cook stew": "Vamos a cocinar guiso",
        "I need soap": "Necesito jabón",
        "I am washing the pan": "Estoy lavando la sartén",
        "Are you working?": "¿Estás trabajando?",
        "I want to go to the beach": "Quiero ir a la playa",
        "Let’s walk today": "Vamos a caminar hoy",
        "I am cutting meat": "Estoy cortando carne",
        "We need food": "Necesitamos comida",
        "I am boiling water": "Estoy hirviendo agua",
        "I like fishing": "Me gusta pescar",
        "Let’s go to the house": "Vamos a la casa",
        "I am going to work": "Voy al trabajo",
        "I need a chair": "Necesito una silla",
        "Are we cooking tonight?": "¿Vamos a cocinar esta noche?",
        "I want to sleep": "Quiero dormir",
        "Let’s see the fish": "Vamos a ver el pescado",
        "I am grilling today": "Estoy asando hoy",
        "We are shopping": "Estamos comprando",
        "What time are we going?": "¿A qué hora vamos?",
        "I need a pot": "Necesito una olla",
        "I am waking up early": "Me despierto temprano",
        "Let’s take the boat": "Vamos a tomar el barco",
        "I like the beach": "Me gusta la playa",
        "I am going to the room": "Voy al cuarto",
        "We need money": "Necesitamos dinero",
        "I want to wash": "Quiero lavar",
        "Are you fishing?": "¿Estás pescando?",
        "I am cooking eggs": "Estoy cocinando huevos",
        "Let’s go to the fire": "Vamos al fuego",
        "I need to know": "Necesito saber"
    }
}